import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header'
import Banner from '../components/Banner/Banner'
import AboutUs from '../components/AboutUs/AboutUs'
import Footer from '../components/Footer/Footer'
import Brands from '../components/Brands/Brands'
import Wrapper from '../components/Wrapper/Wrapper'
import Revenue from '../components/Revenue/Revenue'
import Customers from '../components/Customers/Customers'
import Calculator from '../components/Calculator/Calculator'
import EscaUsers from '../components/EscaUsers/EscaUsers'
import Contact from '../components/Contact/Contact'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Esca</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Wrapper>
        <Banner />
        <Brands />
        <Revenue />
        <Customers />
        <AboutUs />
        <Calculator />
        <EscaUsers />
        <Contact />
      </Wrapper>
    </div>
  )
}
